### PR TITLE
hclpack: fix hclpack decoding nested body

### LINKED ISSUE #72: hclpack: Attributes being mixed up in content()
When multiple blocks have the same type, the attributes within the block are somehow set on the previously decoded blocks too. This is a bit tricky to explain so an example is better:

```go
package main

import (
	"fmt"
	"log"

	"github.com/hashicorp/hcl2/gohcl"
	"github.com/hashicorp/hcl2/hcl"
	"github.com/hashicorp/hcl2/hclpack"
)

func main() {
	src := `
foo {
	bar = "123"
}

foo {
	bar = "abc"
}
`
	
	body, diags := hclpack.PackNativeFile([]byte(src), "file.hcl", hcl.Pos{Line: 1, Column: 1})
	if diags.HasErrors() {
		log.Fatal(diags)
	}

	got := struct {
		Foos []struct {
			Bar string `hcl:"bar"`
		} `hcl:"foo,block"`
	}{}

	diags = gohcl.DecodeBody(body, nil, &got)
	if diags.HasErrors() {
		log.Fatal(diags)
	}

	fmt.Printf("Result: %+v\n", got)
	
	// Output:
	// Result: {Foos:[{Bar:abc} {Bar:abc}]}
}
```

Here I would expect the output to be `Result: {Foos:[{Bar:123} {Bar:abc}]}`.

If we change lines 23-26 to this:

```go
file, diags := hclsyntax.ParseConfig([]byte(src), "file.hcl", hcl.Pos{Byte: 0, Line: 1, Column: 1})
if diags.HasErrors() {
	log.Fatal(diags)
}
body := file.Body
```

The result is what I would expect.

This seems like a bug to me but it's possible I've misunderstood something.

Here's a failing test case:

```diff
diff --git hclpack/structure_test.go hclpack/structure_test.go
index 0d5f11c..78b1037 100644
--- a/hclpack/structure_test.go
+++ b/hclpack/structure_test.go
@@ -75,6 +75,73 @@ func TestBodyContent(t *testing.T) {
 				},
 			},
 		},
+		"block attributes": {
+			&Body{
+				ChildBlocks: []Block{
+					{
+						Type: "foo",
+						Body: Body{
+							Attributes: map[string]Attribute{
+								"bar": {
+									Expr: Expression{
+										Source:     []byte(`"hello"`),
+										SourceType: ExprNative,
+									},
+								},
+							},
+						},
+					},
+					{
+						Type: "foo",
+						Body: Body{
+							Attributes: map[string]Attribute{
+								"bar": {
+									Expr: Expression{
+										Source:     []byte(`"world"`),
+										SourceType: ExprNative,
+									},
+								},
+							},
+						},
+					},
+				},
+			},
+			&hcl.BodySchema{
+				Blocks: []hcl.BlockHeaderSchema{
+					{Type: "foo"},
+				},
+			},
+			&hcl.BodyContent{
+				Blocks: hcl.Blocks{
+					{
+						Type: "foo",
+						Body: &Body{
+							Attributes: map[string]Attribute{
+								"bar": {
+									Expr: Expression{
+										Source:     []byte(`"hello"`),
+										SourceType: ExprNative,
+									},
+								},
+							},
+						},
+					},
+					{
+						Type: "foo",
+						Body: &Body{
+							Attributes: map[string]Attribute{
+								"bar": {
+									Expr: Expression{
+										Source:     []byte(`"world"`),
+										SourceType: ExprNative,
+									},
+								},
+							},
+						},
+					},
+				},
+			},
+		},
 	}
 
 	for name, test := range tests {
@@ -85,7 +152,13 @@ func TestBodyContent(t *testing.T) {
 			}
 
 			if !cmp.Equal(test.Want, got) {
-				t.Errorf("wrong result\n%s", cmp.Diff(test.Want, got))
+				bytesAsString := func(s []byte) string {
+					return string(s)
+				}
+				t.Errorf("wrong result\n%s", cmp.Diff(
+					test.Want, got,
+					cmp.Transformer("bytesAsString", bytesAsString),
+				))
 			}
 		})
 	}
```

### PR DESCRIPTION
**Pull request by akupila**
Fixes an issue where a nested block would be decoded incorrectly, the
body of the last decoded block overwrites the previously decoded ones.

This was caused by the block being assigned on the stack in the `for`
loop; when the block is converted to a *hcl.Block, the pointer to Body
will always point to the same block. This caused decoding a new block to
overwrite the bodies of any previously decoded blocks.

_This is my first PR here, if there's anything else you'd like to see here please let me know._

Fixes #72

### CODE REVIEW

File: hclpack/structure_test.go [hunk 1]
```diff
@@ -85,7 +152,13 @@ func TestBodyContent(t *testing.T) {
 			}
 
 			if !cmp.Equal(test.Want, got) {
-				t.Errorf("wrong result\n%s", cmp.Diff(test.Want, got))
+				bytesAsString := func(s []byte) string {
```
Comment (akupila) [inline hclpack/structure_test.go]: This is not directly relevant to this PR but makes it a bit easier to see what's failing the the test.

Copied from https://github.com/hashicorp/hcl2/blob/master/hclpack/pack_native_test.go#L154

**Comment by apparentlymart** [comment]
Thanks for looking into this, @akupila!

This `hclpack` package is still pretty new/experimental, so I'm sorry you were the one to find these rough edges, and I appreciate you taking the time to dig in and debug them.

It looks like somehow Travis-CI got disconnected from this repository, so I'm going to close and re-open this in the hopes of triggering a Travis-CI run.

**Comment by akupila** [comment]
No worries at all! I really like the idea of hclpack and happy to help smooth out the rough edges
